### ISSUE TITLE
Feature Request: Add option to choose quicklookurl to preview whole site like 1.1.0 or hero image

### ISSUE THREAD

**Issue by olivergiangvu** [chrisgrieser/alfred-anime-search#2]
### Checklist

- [X] I have read the plugin's documentation.
- [X] The feature would be useful to more users than just me.

### Feature Requested

Hi,
Please add option to choose quicklookurl to preview whole site like 1.1.0 or hero image.
The hero image vary a lot on size so the preview panel look not as nice as before and also preview the whole site wil be must more useful in my case and other users- I believe.

Thank for your great work as always.

**Comment by chrisgrieser** [comment]
Good point. I added such a setting in 2.1.0.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-anime-search/releases/download/2.1.0/alfred-anime-search.alfredworkflow
